# Generated by Django 5.2 on 2025-08-27 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckBoxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp')])),
                ('profile_picture', models.ImageField(upload_to='profile_pictures/')),
                ('represent_a_company', models.BooleanField()),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('industry_other', models.CharField(blank=True, max_length=100)),
                ('company_size', models.CharField(blank=True, max_length=10)),
                ('company_website', models.CharField(blank=True, max_length=100)),
                ('project_title', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('category_other', models.CharField(max_length=200)),
                ('budget', models.CharField(max_length=50)),
                ('deadline', models.DateField()),
                ('created_at', models.DateField()),
                ('checkboxes', models.ManyToManyField(blank=True, to='API.checkboxes')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_links', to='API.project')),
            ],
        ),
        migrations.CreateModel(
            name='UploadProjectFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='API.project')),
            ],
        ),
    ]
