# Generated by Django 5.2 on 2025-08-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkboxes',
            name='option',
            field=models.CharField(max_length=100),
        ),
    ]
