# Generated by Django 5.2 on 2025-08-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Mobile App', 'Mobile App'), ('Graphic Design', 'Graphic Design'), ('Writing', 'Writing'), ('Other', 'Other')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='industry',
            field=models.CharField(blank=True, choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('other', 'Other')]),
        ),
    ]
