# Generated by Django 5.2 on 2025-08-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_project_options_alter_checkboxes_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Mobile App', 'Mobile App'), ('Graphic Design', 'Graphic Design'), ('Writing', 'Writing'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='industry',
            field=models.CharField(blank=True, choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='preferred_contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp')], max_length=100),
        ),
    ]
